### PR TITLE
Report unused exports when exposing all

### LINKED ISSUE #82: NoUnused.Exports does not work when exposing all
**Describe the bug**
I'm not sure if this is a bug. Perhaps I don't understand how this rule is supposed to work. At any rate, if you use `NoUnused.Exports.rule` and also expose everything using `exposing (..)`, the rule won't fire.

**SSCCE (Short Self-Contained Correct Example)**
Define a module like this:

``` elm
module Example exposing (..)

unused : ()
unused =
    ()
```

**Expected behavior**
A warning that `unused` is in fact unused. Changing `exposing (..)` to `exposing (unused)` does give the warning:

> Exposed function or value `unused` is never used outside this module.

**Additional context**
I noticed this while developing an application where we've decided to always use `exposing (..)` in order to avoid the busywork of managing exports. After a while, I noticed that things I knew were unused weren't being reported as such by elm-review. It took me a while to discover that `exposing (..)` was the culprit.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #82.

### CODE REVIEW

File: src/NoUnused/Exports.elm [hunk 1]
```diff
@@ -547,6 +553,46 @@ fromProjectToModule =
...
+                    , open = Just range
+                    }
+
+        Declaration.PortDeclaration signature ->
+            signature.name
+                |> Node.value
+                |> Exposing.FunctionExpose
+                |> Just
+
+        Declaration.InfixDeclaration infix ->
```
Comment (tfausak) [inline src/NoUnused/Exports.elm:586]: I'm not sure how to test this. I thought Elm didn't have custom infix operators anymore.

File: src/NoUnused/Exports.elm [hunk 2]
```diff
@@ -547,6 +553,46 @@ fromProjectToModule =
...
+            infix.operator
+                |> Node.value
+                |> Exposing.InfixExpose
+                |> Just
+
+        Declaration.Destructuring _ _ ->
```
Comment (tfausak) [inline src/NoUnused/Exports.elm:592]: It would in theory be possible to implement (some of) this, but it didn't seem worth it.

File: tests/NoUnused/ExportsTest.elm [hunk 3]
```diff
@@ -1021,6 +1012,8 @@ main = text ""
 """
                 , """
 module OtherModule exposing (..)
+import Test
+a : Test.Test
```
Comment (jfmengels) [inline tests/NoUnused/ExportsTest.elm:1016]: I'm guessing this is to prevent `a` from being reported?
If so, you should instead reference it in the `NotReported`, for instance by doing `main = OtherModule.a`.

File: tests/NoUnused/ExportsTest.elm [hunk 4]
```diff
@@ -1239,6 +1233,7 @@ unusedInProductionCode = 2
 module ATest exposing (..)
 import A
 import Test
+a : Test.Test
```
Comment (jfmengels) [inline tests/NoUnused/ExportsTest.elm:1236]: Just to confirm: this is to avoid `a` from being reported in this test, right?

I'm slightly worried about the impact of this PR on tests. Some people don't add type annotations to their values, including their tests. As much as I like adding type annotations myself, I don't want to impose others to do so.

The fact that there is "by chance" no automatic fix here is nice because it won't cause the tests to disappear, which is a bit too easy  if the user does not pay much attention and will be hard to notice after the fact.

I think we should at least add a warning in the description asking the users to either add a type annotation if they want to keep a value that might be a test.

That said, I think we do want to have fixes for this, would you by any chance be up for adding that too? You're allowed to say no :smile:

The automatic fix would be removing the declaration and its potential `@docs` reference (which we already do for other exports), but let's skip the automatic if the module imports `Test` and the element is a value/function without a type annotation. Tests for this would be great.

File: tests/NoUnused/ExportsTest.elm [hunk 5]
```diff
@@ -1549,3 +1545,101 @@ unused = 1
                           )
                         ]
         ]
+
+
+exposingAllTests : Test
+exposingAllTests =
+    describe "When exposing all"
+        [ test "works with a function" <|
```
Comment (jfmengels) [inline tests/NoUnused/ExportsTest.elm:1553]: Thank you for adding tests :pray: 

Would you mind adding some explicit tests where a module exposes everything (if you've noticed such tests somewhere else, feel free to move them here) but nothing gets reported because all their exposed elements are used? I'm thinking one test for functions, one for type alias, etc. just like you did here.
And I think we should do so for both usages in the same file and usages in other files.

File: src/NoUnused/Exports.elm (hunk 1 above)
Comment (jfmengels) [reply src/NoUnused/Exports.elm:586]: `elm-syntax` aims to be able to support code from core packages, hence why this is a possibility, but it's not one we have to consider so this is fine :+1:

File: src/NoUnused/Exports.elm (hunk 2 above)
Comment (jfmengels) [reply src/NoUnused/Exports.elm:592]: This AST node is not possible actually. I aim to remove it in a future major version of `elm-syntax`. Until then we have to live with it... :upside_down_face: 
So the code here is fine :+1:

File: tests/NoUnused/ExportsTest.elm [hunk 6]
```diff
@@ -1549,3 +1545,101 @@ unused = 1
...
+type UnusedT = UnusedC
+"""
+                ]
+                    |> Review.Test.runOnModulesWithProjectData application rule
+                    |> Review.Test.expectErrorsForModules
+                        [ ( "Reported"
+                          , [ Review.Test.error
+                                { message = "Exposed type `UnusedT` is never used outside this module."
+                                , details = unusedExposedElementDetails
+                                , under = ".."
```
Comment (jfmengels) [inline tests/NoUnused/ExportsTest.elm:1617]: `under` should point to `UnusedT` (Same for the other kinds of elements)

**Review by jfmengels — COMMENTED** [review]
Hey @tfausak! Thank you for making this!

I'd love to have a few more tests. I also think the current solution is incomplete, as elements will be reported even if they're used in the same file. That means that people will get errors that they can't do anything about (except not using `exposing (..)`).

If you didn't know, you can try out your changes on your project by running the following command:

```
elm-review --template tfausak/elm-review-unused/preview#gh-82-exposing-all --rules NoUnused.Exports
```

Actually, since you have your changes locally, you can even do it simpler, by using:
```
elm-review --config <path-to-elm-review-unused>/preview --rules NoUnused.Exports
```

**Comment by tfausak** [comment]
Thanks for the quick and thorough feedback! It may take me a while to get to everything.

File: tests/NoUnused/ExportsTest.elm (hunk 6 above)
Comment (tfausak) [reply tests/NoUnused/ExportsTest.elm:1617]: I was wondering where the `Range` should point for these errors. Typically with an unused export, the error would point at the export itself, not the declaration. That's why I decided to point at the `..`. However that probably makes the error less useful since to fix it you have to go find the declaration anyway. I'll update the code to retain the `Range` from the declaration rather than moving it to the `..`.

**Comment by tfausak** [comment]
I haven't yet figured out how to avoid reporting stuff that's only used internally. For a module like this:

``` elm
module Example exposing (..)
used = ()
unused = used
```

This branch will report both `unused` and `used` as unused (assuming neither of them are used by another module). That kind of makes sense if you think of this rule as replacing `exposing (..)` with an explicit list exposing everything defined in the module; `exposing (used, unused)` would indeed be a problem! 

However only `unused` should be reported as a problem. I'm not sure how to pull that off. In English, what I want to say is: If the module is using `exposing (..)`, then anything defined in the module and also used in the module should be counted as "used". 

I'll have to think on this for a bit, but if you've got any ideas then please let me know!

**Comment by jfmengels** [comment]
> I haven't yet figured out how to avoid reporting stuff that's only used internally. For a module like this:

The way to do this is to look at usages for local elements. Thankfully, that's already done in `registerLocalValue`. I think you can edit it a bit like this:

```elm
registerLocalValue : Range -> String -> ModuleContext -> ModuleContext
registerLocalValue range name moduleContext =
    case ModuleNameLookupTable.moduleNameAt moduleContext.lookupTable range of
        Just [] ->
            if moduleContext.isExposingAll then
                { moduleContext | exposed = Dict.remove name moduleContext.exposed }
            else 
            -- the conditions that were already there
```
I *think* that will work. You'll also need to add `isExposingAll` to `ModuleContext` and have it correspond to whether you're exposing everything or not.

**Comment by tfausak** [comment]
I still need to fix the changes to unrelated tests. But I think I've got everything else squared away. Thanks again for the quick and thorough feedback! 

Also let me say that working on this repo has been a joy! I've been very impressed with the output from the test suite. And the command to do an ad hoc run of this branch is awesome. So thanks for putting the effort into making that nice!

**Comment by jfmengels** [comment]
This is starting to look really good, thank you for your work!
I'm not sure what you think is missing still, can you clarify that?

One blocker for this PR for me is deciding whether to hide this new behavior behind a configuration option or not. I'm still on the edge here :thinking:

**Comment by tfausak** [comment]
To be clear, I'm happy with this PR where it is now. I think anything else could be done as future enhancements. But if there's anything else you'd like me to do for this, please let me know!

**Comment by tfausak** [comment]
Unfortunately I've lost the thread on this. Are you waiting on me for something here?

**Comment by jfmengels** [comment]
Hey @tfausak,
Sorry, this was on me. Your PR arrived pretty much around the time that I needed a bit of a OSS break, and I didn't have the energy to make a decision. I'm ready to merge this now, I'll try to polish it up a bit (documentation, etc.) and then I'll release it.
I also noticed that the fix was incorrect sometimes
```
module A exposing (..)
unused = 1
type X = Y
-->
module A exposing (..)
X = Y
```
which I've fixed in a follow-up commit (b1d7fc34013474d01363828b27ea4224b7a7a5f0)

Thank you for your work on this, and sorry for the delay in the response and merge.

**Comment by tfausak** [comment]
No problem at all! Thanks for the help with this PR.
