### PR TITLE
Handle custom type constructors starting with non-ASCII letters

### LINKED ISSUE #78: Wrongly reports custom type constructor starting with a non-ASCII letter as unused
**Describe the bug**
Custom type constructors starting with non-ASCII letters do not seem to ever count as used.

**SSCCE (Short Self-Contained Correct Example)**
1. Clone https://github.com/lydell/elm-review-unused-non-ascii
2. Run `npm cit`
3. See error

**Fast and loose reproduction**

Rename some custom type constructor that you know is used to start with for example `Ö`.

**Expected behavior**
The custom type constructor `Örebro` should not be reported as unused.

**Additional context**
Sweden has 21 regions. I made a custom type for them, naming them like the are named for real in Swedish, with ÅÄÖ. In the SSCCE I only have two of them – `Värmland` and `Örebro`. `Värmland` (which has a non-ASCII letter in the middle) works fine, while `Örebro` (which has a non-ASCII letter at the start) is reported as unused despite being used.

### PR DESCRIPTION
**Pull request by lydell**
Fixes #78.

### CODE REVIEW

File: src/String/Extra.elm [hunk 1]
```diff
@@ -0,0 +1,22 @@
+module String.Extra exposing (isCapitalized)
+
+{-| Some utilities.
+-}
+
+
+{-| Check if the first character of a string is upper case, unicode aware.
+
+Note that `Char.isUpper` is ASCII only, while `Char.isUpper` works outside ASCII.
```
Comment (marc136) [inline src/String/Extra.elm:9]: This comment sounds misleading to me: The first part sounds like `isUpper` "works" on ASCII only, but after the comma it says that it "works with non-ASCII" characters.
But it might be different for native speakers.

```suggestion
Note that `Char.isUpper` is ASCII only, while `Char.toUpper` also works outside ASCII.
See https://github.com/elm/core/pull/1138
```

Or maybe (but I'm not sure if that is fully correct :sweat_smile:)

```suggestion
Note that `Char.isUpper` returns the correct result only for ASCII characters, even though it can be called with any Unicode character.
See https://github.com/elm/core/pull/1138
```

File: src/String/Extra.elm [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+-}
+isCapitalized : String -> Bool
+isCapitalized string =
+    case String.uncons string of
+        Just ( char, _ ) ->
+            -- 1. The character has a lower and upper variant.
+            (Char.toUpper char /= Char.toLower char)
+                -- 2. The character is its upper variant.
+                && (Char.toUpper char == char)
```
Comment (marc136) [inline src/String/Extra.elm:19]: The fix for the core libraries PR from https://github.com/elm/core/pull/1138/files is

```suggestion
            -- 1. The character is its own upper variant.
           (char == Char.toUpper char)
                -- 2. The character is not its own lower variant.
                && (char /= Char.toLower char)

```

But I'm not sure if it really is important if `Char.toLower` is called twice here.

**Review by jfmengels — APPROVED** [review]
Awesome work @lydell! Extra thanks for fixing all the rules instead of just the one that you noticed problems for 😄

File: src/String/Extra.elm (hunk 2 above)
Comment (jfmengels) [reply src/String/Extra.elm:19]: What do you think @lydell? This version does seem a bit better I'd say?

Comment (lydell) [reply src/String/Extra.elm]: Yes, one less `Char.toUpper` call :+1:

**Comment by jfmengels** [comment]
Thank you both! The fix has been released in v1.1.30 :relaxed:
